
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLAVEDER = 6;
  public static final int COMA = 7;
  public static final int ANIO = 2;
  public static final int NAUTOR = 4;
  public static final int EOF = 0;
  public static final int PYC = 8;
  public static final int LIBROS = 11;
  public static final int error = 1;
  public static final int LIBRO = 12;
  public static final int AUTORES = 9;
  public static final int NOMBRE = 3;
  public static final int LLAVEIZQ = 5;
  public static final int EDITORIALES = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ANIO",
  "NOMBRE",
  "NAUTOR",
  "LLAVEIZQ",
  "LLAVEDER",
  "COMA",
  "PYC",
  "AUTORES",
  "EDITORIALES",
  "LIBROS",
  "LIBRO"
  };
}

